import { GoogleGenAI } from "@google/genai";

export interface AnalysisResult {
  style: string;
  elements: string[];
  materials: string;
  renderSuggestion: string;
  imagenPrompt: string;
  scores: {
    composition: number;
    materials: number;
    lighting: number;
    innovation: number;
    proportion: number;
    detail: number;
  };
}

export class ArchitectureService {
  private aiInstance: GoogleGenAI | null = null;

  private get ai(): GoogleGenAI {
    if (!this.aiInstance) {
      const apiKey = (typeof process !== 'undefined' ? process.env?.GEMINI_API_KEY : undefined) || 
                     (import.meta as any).env.VITE_GEMINI_API_KEY;
      
      if (!apiKey) {
        throw new Error("GEMINI_API_KEY is missing. Please set it in your environment variables via the Settings menu.");
      }
      this.aiInstance = new GoogleGenAI({ apiKey });
    }
    return this.aiInstance;
  }

  async analyzeImage(base64Image: string, mimeType: string, lang: 'EN' | 'VI' = 'EN'): Promise<string> {
    const systemInstruction = `
      You are a senior architectural analysis expert from the "HIGHLANDS AI Studio" system. 
      Your mission is to perform "Architecture Vision System" – scanning images and providing accurate, professional technical assessments.
      
      Respond STRICTLY in ${lang === 'VI' ? 'Vietnamese' : 'English'}.

      Analysis Framework (Must return exactly in this Markdown structure):

      ### ${lang === 'VI' ? 'PHONG CÁCH KIẾN TRÚC' : 'ARCHITECTURAL STYLE'} (Style)
      Identify the style (e.g., Modernism, Tropical, Indochine, Minimalism...).
      Describe the main identifying characteristics in 3 professional sentences.
      **Tags:** [10 architectural keywords in English, separated by commas].

      ### ${lang === 'VI' ? 'YẾU TỐ KIẾN TRÚC' : 'ARCHITECTURAL ELEMENTS'} (Elements)
      List 8 specific details appearing in the image (Windows, roof, balcony, column system, greenery...). Use a bulleted list.

      ### ${lang === 'VI' ? 'VẬT LIỆU & ÁNH SÁNG' : 'MATERIALS & LIGHTING'} (Materials & Space)
      *   **${lang === 'VI' ? 'Vật liệu & Kết cấu' : 'Materials & Texture'}:** Describe surface details (Exposed concrete, natural wood, Low-E glass...).
      *   **${lang === 'VI' ? 'Màu sắc & Tông' : 'Color & Tone'}:** Analyze the dominant color palette.
      *   **${lang === 'VI' ? 'Ánh sáng & Không gian' : 'Lighting & Space'}:** Assess how lighting affects the volumes and forms.

      ### ${lang === 'VI' ? 'ĐỀ XUẤT RENDER' : 'RENDER SUGGESTION'} (Render Suggestion)
      Provide advice to upgrade this image to be more beautiful (Camera angle, time of day...).

      ### IMAGEN 3 RENDER PROMPT
      Write a deep, professional English Prompt for Imagen 3.
      Prompt structure requirements: [Subject description] + [Architectural style] + [Materials details] + [Lighting conditions (e.g., Golden hour, Cinematic lighting)] + [Camera settings (e.g., Wide angle, 8k, f/2.8)] + [Environment/Atmosphere].
      Goal: Create a photorealistic and high-class render.

      ### ${lang === 'VI' ? 'THANG ĐIỂM THIẾT KẾ' : 'DESIGN SCORES'} (Design Scores)
      Return as a Markdown table:
      | ${lang === 'VI' ? 'Tiêu chí' : 'Criterion'} | ${lang === 'VI' ? 'Điểm' : 'Score'} (0-100) |
      | :--- | :--- |
      | ${lang === 'VI' ? 'Bố cục' : 'Composition'} | [Score] |
      | ${lang === 'VI' ? 'Vật liệu' : 'Materials'} | [Score] |
      | ${lang === 'VI' ? 'Ánh sáng' : 'Lighting'} | [Score] |
      | ${lang === 'VI' ? 'Sáng tạo' : 'Innovation'} | [Score] |
      | ${lang === 'VI' ? 'Tỷ lệ' : 'Proportion'} | [Score] |
      | ${lang === 'VI' ? 'Chi tiết' : 'Detail'} | [Score] |
    `;

    const response = await this.ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: [
        {
          parts: [
            { text: lang === 'VI' ? "Hãy phân tích hình ảnh kiến trúc này theo đúng framework được yêu cầu." : "Please analyze this architectural image according to the required framework." },
            {
              inlineData: {
                data: base64Image.split(",")[1] || base64Image,
                mimeType: mimeType,
              },
            },
          ],
        },
      ],
      config: {
        systemInstruction,
        temperature: 0.7,
      },
    });

    if (!response.candidates || response.candidates.length === 0) {
      throw new Error("Analysis failed: No content generated by AI.");
    }

    return response.text || "Analysis failed: Model returned empty text.";
  }

  async chatAboutArchitecture(base64Image: string, mimeType: string, question: string, lang: 'EN' | 'VI' = 'EN'): Promise<string> {
    const systemInstruction = `
      You are a senior architectural consultant from the "HIGHLANDS AI Studio".
      A user is asking a specific question/requirement about an architectural image or a project.
      
      Your goal is to provide professional, actionable architectural suggestions, improvements, or explanations.
      
      Respond STRICTLY in ${lang === 'VI' ? 'Vietnamese' : 'English'}.
      Format your response with Markdown. Use bullet points for suggestions.
      Keep the tone professional, helpful, and concise.
    `;

    const response = await this.ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: [
        {
          parts: [
            { text: `CONTEXT: User is asking about their architectural design. 
                     QUESTION: ${question}` },
            {
              inlineData: {
                data: base64Image.split(",")[1] || base64Image,
                mimeType: mimeType,
              },
            },
          ],
        },
      ],
      config: {
        systemInstruction,
        temperature: 0.8,
      },
    });

    if (!response.candidates || response.candidates.length === 0) {
      throw new Error("Chat failed: No content generated by AI.");
    }

    return response.text || "Chat failed: Model returned empty text.";
  }

  async analyzeContextInformation(
    documentAssets: { base64: string; mimeType: string; name: string }[],
    imageAssets: { base64: string; mimeType: string }[]
  ): Promise<{ analysis: string; tags: string[] }> {
    const parts: any[] = [];
    
    // Add text documents
    if (documentAssets.length > 0) {
      parts.push({
        text: 'Here are the reference documents provided by the user:'
      });
      documentAssets.forEach((doc) => {
        parts.push({
          inlineData: {
            data: doc.base64.split(",")[1] || doc.base64,
            mimeType: doc.mimeType || "text/plain",
          },
        });
      });
    }
    
    // Add image assets
    if (imageAssets.length > 0) {
      parts.push({
        text: 'Here are the visual references from the user:'
      });
      imageAssets.forEach((img) => {
        parts.push({
          inlineData: {
            data: img.base64.split(",")[1] || img.base64,
            mimeType: img.mimeType,
          },
        });
      });
    }
    
    parts.push({
      text: `Please analyze the provided documents and visual references carefully. 
Extract the core architectural brand DNA, material correlations, style, and key elements present in these resources.
Keep the analysis concise, professional, and insightful.

Output your response strictly as a JSON object with this structure:
{
  "analysis": "A concise paragraph summarizing the key architectural/design themes, styles, and elements found.",
  "tags": ["Tag 1", "Tag 2", "Tag 3", "Tag 4", "Tag 5"]
}
Do not use markdown formatting like \`\`\`json. Return only valid JSON.`
    });

    try {
      const response = await this.ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: [{ parts }],
        config: {
          temperature: 0.2, // Low temperature for more analytical output
          responseMimeType: "application/json",
        },
      });

      if (!response.candidates || response.candidates.length === 0) {
        throw new Error("No response from AI model.");
      }

      const text = response.text || "{}";
      const parsed = JSON.parse(text);
      return {
        analysis: parsed.analysis || "No clear themes could be extracted.",
        tags: parsed.tags || []
      };
    } catch (error) {
      console.error("Context analysis error:", error);
      return {
        analysis: "Failed to analyze context resources. Please ensure files are valid.",
        tags: ["Error"]
      };
    }
  }

  async generateRenderImage(
    prompt: string, 
    baseImage?: string, 
    mimeType?: string, 
    model: string = 'gemini-3.1-flash-image-preview', 
    aspectRatio: string = '1:1'
  ): Promise<string> {
    try {
      // Determine if we should use generateContent (multimodal) or generateImages (Imagen-only)
      const isImagen = model.toLowerCase().includes('imagen');
      
      if (isImagen) {
        const response = await this.ai.models.generateImages({
          model: model,
          prompt: prompt,
          config: {
            numberOfImages: 1,
            aspectRatio: aspectRatio as any,
          },
        });

        if (!response.generatedImages || response.generatedImages.length === 0) {
          throw new Error("No image generated by Imagen model.");
        }

        return `data:image/png;base64,${response.generatedImages[0].image.imageBytes}`;
      } else {
        // Nano Banana series (Gemini Vision + Generation) models use generateContent
        const parts: any[] = [];
        
        if (baseImage && mimeType) {
          parts.push({
            inlineData: {
              data: baseImage.split(",")[1] || baseImage,
              mimeType: mimeType,
            },
          });
        }
        
        parts.push({ text: prompt });

        const response = await this.ai.models.generateContent({
          model: model,
          contents: [{ parts }],
          config: {
            imageConfig: {
              aspectRatio: aspectRatio as any,
            },
          },
        });

        if (!response.candidates || response.candidates.length === 0) {
          throw new Error("No response from generation model.");
        }

        for (const part of response.candidates[0].content.parts) {
          if (part.inlineData) {
            return `data:image/png;base64,${part.inlineData.data}`;
          }
        }
        
        throw new Error("The AI model did not return an image part.");
      }
    } catch (error: any) {
      console.error("Error in generateRenderImage:", error);
      throw error;
    }
  }
}

export const architectureService = new ArchitectureService();
